In [1]:
import numpy as np

In [3]:
print(np.__version__)   #打印numpy的配置
np.show_config()        #numpy配置说明

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda\\Library\\include']
blas

In [5]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
z = np.zeros((10,10))                     #计算一个数组的内存大小
print("%d bytes"%(z.size*z.itemsize))

800 bytes


In [10]:
np.info(np.add)                 #从命令行得到numpy中add函数的说明文档

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [11]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [13]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [16]:
a = np.array([1,2,3.4,5])
a = a[::-1]
a

array([5. , 3.4, 2. , 1. ])

In [19]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
nz = np.nonzero([1,2,0,0,4,0])       #找到数组的非0元素的位置索引
nz

(array([0, 1, 4], dtype=int64),)

In [21]:
a = np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
c = 10*np.random.random((3,3,3))
c

array([[[6.03603458, 5.26115354, 1.44717351],
        [7.96332556, 7.32298905, 4.85578532],
        [8.01233622, 4.16131428, 4.91363398]],

       [[2.34682715, 0.56477052, 7.93841626],
        [8.26333227, 5.14643566, 1.42398568],
        [3.38712245, 0.65715242, 2.26756648]],

       [[1.32308394, 7.26473363, 3.7357459 ],
        [4.05727238, 4.74218855, 8.73532284],
        [5.93430743, 2.37077685, 2.28664787]]])

In [42]:
d = np.random.random((10,10))
d.min()
d.max()

0.012596411500003457

In [44]:
a = np.random.random(30)
a.mean()

0.456354228911441